import { Router } from 'express';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import db from '../db.js';
import { getPromptContent, savePromptVersion, currentPromptVersion } from '../services/promptStore.js';
import { improveContentPrompt } from '../services/editorial.js';

function getShowCriteria() {
  return db.prepare('SELECT criteria_text FROM show_criteria WHERE id = 1').get()?.criteria_text ?? '';
}

function getKeepList() {
  return db.prepare('SELECT id, pattern, reason, created_at FROM keep_list ORDER BY created_at DESC').all();
}

// Feedback collected on outputs generated by this prompt (content_type === prompt name).
function getFeedbackSummary(name) {
  const counts = db.prepare(`
    SELECT
      COUNT(*) AS total,
      SUM(CASE WHEN rating > 0 THEN 1 ELSE 0 END) AS up,
      SUM(CASE WHEN rating < 0 THEN 1 ELSE 0 END) AS down,
      SUM(CASE WHEN note IS NOT NULL AND TRIM(note) != '' THEN 1 ELSE 0 END) AS notes
    FROM content_feedback WHERE content_type = ?
  `).get(name);
  const recentNotes = db.prepare(`
    SELECT rating, note, created_at FROM content_feedback
    WHERE content_type = ? AND note IS NOT NULL AND TRIM(note) != ''
    ORDER BY created_at DESC LIMIT 10
  `).all(name);
  return {
    total: counts?.total || 0,
    up: counts?.up || 0,
    down: counts?.down || 0,
    notes: counts?.notes || 0,
    recentNotes,
  };
}

function getPendingSuggestion(name) {
  return db.prepare(`
    SELECT id, suggested_content, reasoning, created_at FROM prompt_suggestions
    WHERE prompt_name = ? AND status = 'pending' ORDER BY created_at DESC LIMIT 1
  `).get(name);
}

// Compact text digest of feedback to feed the improver.
function feedbackDigest(summary) {
  const lines = [`Ratings: ${summary.up} positive, ${summary.down} negative (of ${summary.total} total).`];
  if (summary.recentNotes.length) {
    lines.push('Written notes:');
    for (const n of summary.recentNotes) {
      const mark = n.rating > 0 ? '(liked)' : n.rating < 0 ? '(disliked)' : '(neutral)';
      lines.push(`- ${mark} ${n.note.trim()}`);
    }
  }
  return lines.join('\n');
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const promptsDir = join(__dirname, '..', 'prompts');

const PROMPTS = [
  { name: 'rahul-x',        label: "Rahul's X",        file: 'rahul-x.txt' },
  { name: 'gautham-x',      label: "Gautham's X",       file: 'gautham-x.txt' },
  { name: 'brand-x',        label: 'Brand X',           file: 'brand-x.txt' },
  { name: 'x-article',      label: 'X Article',         file: 'x-article.txt' },
  { name: 'linkedin',       label: 'LinkedIn',          file: 'linkedin.txt' },
  { name: 'youtube',        label: 'YouTube',           file: 'youtube.txt' },
  { name: 'youtube-description', label: 'YouTube Description', file: 'youtube-description.txt' },
  { name: 'substack-show-notes', label: 'Substack Show Notes', file: 'substack-show-notes.txt' },
  { name: 'editorial-pass1', label: 'Editorial Pass 1', file: 'editorial-pass1.txt' },
  { name: 'editorial-pass2', label: 'Editorial Pass 2', file: 'editorial-pass2.txt' },
  { name: 'intro-script',    label: 'Intro Script',     file: 'intro-script.txt' },
];

const PROMPT_BY_NAME = new Map(PROMPTS.map((p) => [p.name, p]));

const router = Router();

router.get('/settings/prompts', (req, res) => {
  const prompts = PROMPTS.map((p) => {
    const defaultContent = readFileSync(join(promptsDir, p.file), 'utf-8');
    const row = db.prepare('SELECT content FROM prompts WHERE name = ?').get(p.name);
    return {
      ...p,
      content: row ? row.content : defaultContent,
      isCustom: !!row,
      defaultContent,
      version: currentPromptVersion(p.name),
      feedback: getFeedbackSummary(p.name),
      suggestion: getPendingSuggestion(p.name),
    };
  });

  res.render('prompts', {
    title: 'Prompts',
    prompts,
    saved: req.query.saved || null,
    reset: req.query.reset || null,
    tuned: req.query.tuned || null,
    nochange: req.query.nochange || null,
    criteria: getShowCriteria(),
    keepList: getKeepList(),
  });
});

router.post('/settings/prompts/:name', (req, res) => {
  const { name } = req.params;
  const { content } = req.body;
  if (!PROMPT_BY_NAME.has(name)) return res.status(404).send('Unknown prompt');

  savePromptVersion(name, (content || '').trim(), 'manual edit');
  res.redirect(`/settings/prompts?saved=${name}`);
});

router.post('/settings/prompts/:name/reset', (req, res) => {
  const { name } = req.params;
  if (!PROMPT_BY_NAME.has(name)) return res.status(404).send('Unknown prompt');

  db.prepare('DELETE FROM prompts WHERE name = ?').run(name);
  res.redirect(`/settings/prompts?reset=${name}`);
});

// ─── Improve prompt from collected feedback ──────────────────────────────────

router.post('/settings/prompts/:name/tune', async (req, res, next) => {
  try {
    const { name } = req.params;
    const meta = PROMPT_BY_NAME.get(name);
    if (!meta) return res.status(404).send('Unknown prompt');

    const summary = getFeedbackSummary(name);
    if (summary.total === 0) return res.redirect(`/settings/prompts?tuned=${name}&nochange=1`);

    const current = getPromptContent(name, meta.file);
    const result = await improveContentPrompt(meta.label, current, feedbackDigest(summary));

    if (!result?.proposed || result.proposed.trim() === current.trim()) {
      return res.redirect(`/settings/prompts?tuned=${name}&nochange=1`);
    }

    db.prepare(`
      INSERT INTO prompt_suggestions (prompt_name, suggested_content, reasoning, status)
      VALUES (?, ?, ?, 'pending')
    `).run(name, result.proposed, result.summary || '');

    res.redirect(`/settings/prompts?tuned=${name}`);
  } catch (err) { next(err); }
});

router.post('/settings/prompts/:name/apply-suggestion', (req, res) => {
  const { name } = req.params;
  if (!PROMPT_BY_NAME.has(name)) return res.status(404).send('Unknown prompt');

  const suggestion = getPendingSuggestion(name);
  if (!suggestion) return res.redirect(`/settings/prompts?tuned=${name}`);

  savePromptVersion(name, suggestion.suggested_content, 'tuned from feedback');
  db.prepare(`UPDATE prompt_suggestions SET status = 'applied', resolved_at = datetime('now') WHERE id = ?`)
    .run(suggestion.id);

  res.redirect(`/settings/prompts?saved=${name}`);
});

router.post('/settings/prompts/:name/dismiss-suggestion', (req, res) => {
  const { name } = req.params;
  if (!PROMPT_BY_NAME.has(name)) return res.status(404).send('Unknown prompt');

  const suggestion = getPendingSuggestion(name);
  if (suggestion) {
    db.prepare(`UPDATE prompt_suggestions SET status = 'dismissed', resolved_at = datetime('now') WHERE id = ?`)
      .run(suggestion.id);
  }
  res.redirect(`/settings/prompts?tuned=${name}`);
});

export default router;
